# üìç Problem Title: Patients With a Condition

üîó [LeetCode 1527 ‚Äì Patients With a Condition](https://leetcode.com/problems/patients-with-a-condition/description/?envType=study-plan-v2&envId=30-days-of-pandas)

## üóÇÔ∏è Category
- Topic: **String Matching**, **Condition Checking**
- Difficulty: ‚≠ê Easy

## üìù Problem Description
We are given a table of patients with their **ID**, **name**, and a space-separated list of **conditions**.
We need to find patients who have **at least one condition that starts with `DIAB1`**.

Return all columns for those patients.

## üßæ Example

### Input
| patient_id | name     | conditions         |
|------------|----------|--------------------|
| 1          | Alice    | DIAB100 DIAB200    |
| 2          | Bob      | DIAB1 HYP2         |
| 3          | Charlie  | ASTHMA DIAB123     |
| 4          | David    | COLD FLU           |
| 5          | Eve      | DIAB1 DIAB2        |

### Output
| patient_id | name    | conditions         |
|------------|---------|--------------------|
| 1          | Alice   | DIAB100 DIAB200    |
| 2          | Bob     | DIAB1 HYP2         |
| 3          | Charlie | ASTHMA DIAB123     |
| 5          | Eve     | DIAB1 DIAB2        |

## üß† Key Concepts
- Splitting strings into individual conditions
- Checking if any condition starts with a specific prefix
- Filtering rows based on custom logic

In [2]:
import pandas as pd

data = [
    [1, "Alice", "DIAB100 DIAB200"],
    [2, "Bob", "DIAB1 HYP2"],
    [3, "Charlie", "ASTHMA DIAB123"],
    [4, "David", "COLD FLU"],
    [5, "Eve", "DIAB1 DIAB2"],
    [6, "Frank", "HYPERTENSION"]
]

patients = pd.DataFrame(data, columns=["patient_id", "name", "conditions"])
patients

   patient_id     name       conditions
0           1    Alice  DIAB100 DIAB200
1           2      Bob       DIAB1 HYP2
2           3  Charlie   ASTHMA DIAB123
3           4    David         COLD FLU
4           5      Eve      DIAB1 DIAB2
5           6    Frank     HYPERTENSION

In [4]:
def find_patients(patients: pd.DataFrame) -> pd.DataFrame:

    def control_prefix(conditions : str) -> bool:

        patient_conditions = conditions.split(" ")
        for condition in patient_conditions:
            if condition.startswith("DIAB1"):
                return True
        return False

    result_df = patients[patients["conditions"].apply(control_prefix)]

    return result_df

find_patients(patients)

   patient_id     name       conditions
0           1    Alice  DIAB100 DIAB200
1           2      Bob       DIAB1 HYP2
2           3  Charlie   ASTHMA DIAB123
4           5      Eve      DIAB1 DIAB2